[package]
name = "seahorse-learn-0"
version = "0.1.0"
authors = ["hota1024 <hotalog@hota1024.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
seahorse = "1.0.0"
